# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-05-09 20:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postelo', '0002_auto_20170509_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_trash',
            field=models.BooleanField(default=False),
        ),
    ]
