# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-03 22:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordinem', '0002_auto_20170404_0332'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ngo',
            old_name='user',
            new_name='moderator',
        ),
        migrations.AddField(
            model_name='ngo',
            name='address',
            field=models.CharField(default='Vadodara', max_length=500),
        ),
        migrations.AddField(
            model_name='ngo',
            name='category',
            field=models.CharField(default='Children', max_length=50),
        ),
        migrations.AddField(
            model_name='ngo',
            name='contact_no',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ngo',
            name='email',
            field=models.EmailField(default='name@emample.com', max_length=254),
        ),
        migrations.AddField(
            model_name='ngo',
            name='logo',
            field=models.ImageField(null=True, upload_to='logos/'),
        ),
        migrations.AddField(
            model_name='ngo',
            name='web_url',
            field=models.URLField(default='web link'),
        ),
    ]
