# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-11 12:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordinem', '0003_auto_20170404_0342'),
    ]

    operations = [
        migrations.AddField(
            model_name='ngo',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
