# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-17 12:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ordinem', '0004_ngo_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='HapComments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('time_stamp', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('comment_on', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ordinem.Happening')),
            ],
        ),
    ]
