# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-05-08 10:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordinem', '0006_auto_20170417_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='ngo',
            name='bio',
            field=models.TextField(null=True),
        ),
    ]
