# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-05-10 22:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ordinem', '0008_auto_20170510_2121'),
    ]

    operations = [
        migrations.CreateModel(
            name='NgoRatings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('ngo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings_of', to='ordinem.Ngo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
