# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-05-11 18:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ordinem', '0009_ngoratings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ngo',
            name='likes',
        ),
        migrations.AddField(
            model_name='ngo',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
