# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-05-12 19:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ordinem', '0010_auto_20170512_0027'),
    ]

    operations = [
        migrations.AddField(
            model_name='happening',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='thumbs_up_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
